# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

#https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  ProjectName: 'Brimborium.Registrator'
  SolutionPath: 'Brimborium.Registrator/Brimborium.Registrator.sln'
  ProjectPath: 'Brimborium.Registrator/**/*.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: 'restore $(ProjectName)'
  inputs:
    command: restore
    arguments: --configuration $(buildConfiguration)
    projects: $(SolutionPath)

- task: DotNetCoreCLI@2
  displayName: 'build $(ProjectName)'
  inputs:
    command: build
    arguments: --configuration $(buildConfiguration)
    projects: $(SolutionPath)
    includesymbols: true 

- task: DotNetCoreCLI@2
  displayName: 'test $(ProjectName)'
  inputs:
    command: test
    arguments: --configuration $(buildConfiguration)
    projects: $(SolutionPath)

- task: DotNetCoreCLI@2
  displayName: 'pack $(ProjectName)'
  inputs:
    command: pack
    arguments: --configuration $(buildConfiguration)
    projects: $(SolutionPath)
    includesymbols: true 
    nobuild: true
 
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '98a3cab6-96a1-42fc-9f66-561fe90ed4c9/2f2cd7a7-e639-4a69-bac2-0284d0b5f91b'
    allowPackageConflicts: true
#