# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

#https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops

trigger:
- main

pool:
  vmImage: windows-2022

variables:
  buildConfiguration: 'Release'
  ProjectName: 'Brimborium.Net'
  SolutionPath: 'Brimborium.Net.sln'
  projects: |
    Brimborium.CodeBlocks\Brimborium.CodeBlocks.Library\Brimborium.CodeBlocks.Library.csproj
    Brimborium.CodeFlow\Brimborium.CodeFlow\Brimborium.CodeFlow.csproj
    Brimborium.CodeFlow\Brimborium.CodeFlow.Abstracts\Brimborium.CodeFlow.Abstracts.csproj
    Brimborium.Registrator\Brimborium.Registrator\Brimborium.Registrator.csproj
    Brimborium.Registrator\Brimborium.Registrator.Abstractions\Brimborium.Registrator.Abstractions.csproj
    Brimborium.TypedSql\Brimborium.GenerateStoredProcedure\Brimborium.GenerateStoredProcedure.csproj
    Brimborium.TypedSql\Brimborium.SqlAccess\Brimborium.SqlAccess.csproj
    Brimborium.TypedSql\Brimborium.TypedStoredProcedure\Brimborium.TypedStoredProcedure.csproj

  later: |
    Brimborium.CodeBlocks\Brimborium.Typing\Brimborium.Typing.csproj
    Brimborium.WebDavServer\Brimborium.WebDav.WebApp\Brimborium.WebDav.WebApp.csproj
    Brimborium.WebDavServer\Brimborium.WebDavServer\Brimborium.WebDavServer.csproj
    Brimborium.WebDavServer\Brimborium.WebDavServer.Model\Brimborium.WebDavServer.Model.csproj
    Brimborium.WebFlow\Brimborium.WebFlow\Brimborium.WebFlow.csproj
    Brimborium.WebFlow\Brimborium.WebFlow.Abstracts\Brimborium.WebFlow.Abstracts.csproj
    Brimborium.WebFlow\Brimborium.WebFlow.Web\Brimborium.WebFlow.Web.csproj
    Brimborium.WebSocket\Brimborium.WebSockets\Brimborium.WebSockets.csproj



steps:
- task: DotNetCoreCLI@2
  displayName: 'restore $(ProjectName)'
  inputs:
    command: restore
    arguments: --configuration $(buildConfiguration)
    projects: $(projects)
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'
    #vstsFeed: 'https://grimmuko.pkgs.visualstudio.com/Brimborium.Net/_packaging/Brimborium.Net/nuget/v3/index.json'

- task: DotNetCoreCLI@2
  displayName: 'build $(ProjectName)'
  inputs:
    command: build
    arguments: --configuration $(buildConfiguration)
    projects: $(projects)
    includesymbols: true 

- task: DotNetCoreCLI@2
  displayName: 'test $(ProjectName)'
  inputs:
    command: test
    arguments: --configuration $(buildConfiguration)
    projects: $(projects)

#- task: DotNetCoreCLI@2
#  displayName: 'pack $(ProjectName)'
#  inputs:
#    command: pack
#    arguments: --configuration $(buildConfiguration)
#    projects: $(projects)
#    includesymbols: true 
 
- task: DotNetCoreCLI@2
  displayName: 'pack Brimborium.CodeBlocks.Library'
  inputs:
    command: 'pack'
    packagesToPack: 'Brimborium.CodeBlocks\Brimborium.CodeBlocks.Library\Brimborium.CodeBlocks.Library.csproj'
    nobuild: true
    includesymbols: true

- task: DotNetCoreCLI@2
  displayName: 'pack Brimborium.CodeBlocks.Library'
  inputs:
    command: 'pack'
    packagesToPack: 'Brimborium.CodeBlocks\Brimborium.CodeBlocks.Library\Brimborium.CodeBlocks.Library.csproj'
    nobuild: true
    includesymbols: true

- task: DotNetCoreCLI@2
  displayName: 'pack Brimborium.CodeFlow'
  inputs:
    command: 'pack'
    packagesToPack: 'Brimborium.CodeFlow\Brimborium.CodeFlow\Brimborium.CodeFlow.csproj'
    nobuild: true
    includesymbols: true

- task: DotNetCoreCLI@2
  displayName: 'pack Brimborium.CodeFlow.Abstracts'
  inputs:
    command: 'pack'
    packagesToPack: 'Brimborium.CodeFlow\Brimborium.CodeFlow.Abstracts\Brimborium.CodeFlow.Abstracts.csproj'
    nobuild: true
    includesymbols: true

- task: DotNetCoreCLI@2
  displayName: 'pack Brimborium.Registrator'
  inputs:
    command: 'pack'
    packagesToPack: 'Brimborium.Registrator\Brimborium.Registrator\Brimborium.Registrator.csproj'
    nobuild: true
    includesymbols: true

- task: DotNetCoreCLI@2
  displayName: 'pack Brimborium.Registrator.Abstractions'
  inputs:
    command: 'pack'
    packagesToPack: 'Brimborium.Registrator\Brimborium.Registrator.Abstractions\Brimborium.Registrator.Abstractions.csproj'
    nobuild: true
    includesymbols: true

- task: DotNetCoreCLI@2
  displayName: 'pack Brimborium.GenerateStoredProcedure'
  inputs:
    command: 'pack'
    packagesToPack: 'Brimborium.TypedSql\Brimborium.GenerateStoredProcedure\Brimborium.GenerateStoredProcedure.csproj'
    nobuild: true
    includesymbols: true

- task: DotNetCoreCLI@2
  displayName: 'pack Brimborium.SqlAccess'
  inputs:
    command: 'pack'
    packagesToPack: 'Brimborium.TypedSql\Brimborium.SqlAccess\Brimborium.SqlAccess.csproj'
    nobuild: true
    includesymbols: true

- task: DotNetCoreCLI@2
  displayName: 'pack Brimborium.TypedStoredProcedure'
  inputs:
    command: 'pack'
    packagesToPack: 'Brimborium.TypedSql\Brimborium.TypedStoredProcedure\Brimborium.TypedStoredProcedure.csproj'
    nobuild: true
    includesymbols: true

   
    #versioningScheme: 'off'
    #verbosityPack: 'Diagnostic'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '98a3cab6-96a1-42fc-9f66-561fe90ed4c9/2f2cd7a7-e639-4a69-bac2-0284d0b5f91b'
    allowPackageConflicts: true
#