global using global::System;
global using global::System.Collections.Generic;
global using global::System.Diagnostics;
global using global::System.Linq;
global using global::System.Runtime.CompilerServices;
global using global::System.Text;
global using global::Microsoft.CodeAnalysis;
global using global::Microsoft.CodeAnalysis.CSharp;
global using global::Microsoft.CodeAnalysis.CSharp.Syntax;
